name:                meta-springs
version:             0.1.0.0
github:              "tpapak/meta-springs"
license:             GPL-3
author:              "Thodoris Papakonstantinou"
maintainer:          "hi@tpapak.com"
copyright:           "Thodoris Papakonstantinou, 2019"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Meta-analysis as mechanical system
category:            Biostatistics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tpapak/meta-springs#readme>

dependencies:
- base >= 4.7 && < 5
- meta-analysis >= 0.1.6.1
- diagrams
- diagrams-lib
- diagrams-svg >= 1.4.2
- graph >= 0.4.0.0

library:
  source-dirs: src
  dependencies:
   - containers
   - text
   - split

executables:
  meta-springs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - meta-springs

tests:
  meta-springs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - meta-springs
    - cassava
    - aeson
    - vector
    - tesths
    - bytestring
    - containers
